ci:
  autoupdate_schedule: monthly

exclude: qtpy/|test/fixtures/|\.rtf$|PkgInfo$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: share/doc/git-cola
        # For some reason, this file fails
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        name: Enforce Python 3.9 idioms
        args:
          - --py39-plus

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      # sort imports
      - id: ruff-check
        args: [--fix, --select, I]
        files: ^(cola)/
      # format codes
      - id: ruff-format
        args: [--check]
        files: ^(cola)/
        types_or: [ python, pyi ]
      # format codes
      - id: ruff-format
        args: [--diff]
        files: ^(cola)/
        types_or: [ python, pyi ]
      # format codes
      - id: ruff-format
        args: []
        files: ^(cola)/
        types_or: [ python, pyi ]
