#!/bin/sh
./todo/update-qtpy ~/src/python/qtpy
make check
./todo/set-version vA.B.C
./todo/commit-version
# remove any (BETA) markers from the release notes
./todo/tag vA.B.C
git cola push
vx env39 ./todo/release --all
vim github.io/_config.yaml
./todo/github.io.sh
