#!/bin/sh

username=
password=
hostname=ftp.tuxfamily.org
basedir=/gitcola/cola.tuxfamily.org-web/htdocs
all=false
src="$PWD"

usage () {
	echo
	echo "usage: $(basename $0) [options] -u <user> -p <password> [<directory>...]"
	echo "options:"
	echo "--hostname <hostname>  - specify the ftp host"
	echo "                         default: ftp.tuxfamily.org"
	echo "--all                  - synchronize the entire source directory"
	echo "                         default: false"
	echo "--src      <directory> - specify the source directory"
	echo "                         default: current directory"
	echo "[<path>...]            - specify zero or more paths to upload"
	echo "                         ignored by --all"
	echo
	exit -1
}

while test $# -gt 0
do
	case "$1" in
	--host)
		shift
		hostname="$1"
		shift
		;;
	-u)
		shift
		username="$1"
		shift
		;;
	-p)
		shift
		password="$1"
		shift
		;;
	--all)
		shift
		all=true
		;;
	--src)
		shift
		src="$1"
		shift
		;;
	-h|--help)
		usage
		;;
	--)
		shift
		break
		;;
	*)
		break
		;;
	esac
done

upload () {
	cmd=
	for path in "$@"
	do
		if test -d "$path"
		then
			cmd="$cmd""mirror --delete -n -R $directory $basedir/$directory;"
		fi

		if test -f "$path"
		then
			dirname="$(dirname "$path")"
			if test "$dirname" = "."
			then
				subdir=
			else
				subdir="$dirname/"
			fi
			cmd="$cmd""echo; echo transfering $path;"
			cmd="$cmd""cd $basedir/$subdir;"
			cmd="$cmd""put $path;"
		fi
	done
	cmd="$cmd""exit"
	lftp ftp://$hostname -u $username,$password -e "$cmd"
}

if "$all"
then
	lftp ftp://$hostname -u $username,$password \
		-e "mirror --delete -n -R $src $basedir; exit"
else
	upload "$@"
fi
