#!/bin/sh

branch="$1"
pull="$2"

commit=$(git rev-parse "$branch") &&
msg=$(
	echo "$commit		$branch" |
	git fmt-merge-msg --log |
	sed -e "s,Merge $branch,Merge pull request #$pull from $branch," |
	grep -v '^#'
) &&
git merge --no-ff --no-commit "$branch" &&
git commit -m"$msg" --signoff
