#!/bin/sh
. $(dirname $0)/common.sh

# Options
do_docs=false
do_website=false
do_tarball=false
do_win32=false

usage() {
	echo "$(basename "$0") [options]"
	echo
	echo "options:"
	echo "--all                     - build tarball, win32, docs, and web"
	echo "--tarball                 - build the tarball"
	echo "--tarball-dir             - specify the tarball release directory"
	echo "--doc                     - build the documentation"
	echo "--doc-dir <dir>           - specify the documentation directory"
	echo "--win32                   - build the win32 installer"
	echo "--win32-login <user@host> - specify the win32 host"
	echo "--win32-port <port #>     - specify the win32 ssh port number"
	echo "--win32-cola-dir <dir>    - specify the win32 cola repo path"
	echo "--win32-python-dir <dir>  - specify the win32 python directory"
	exit 1
}

build_docs() {
	title Building docs
	do_or_die make prefix="$DOCUMENT_ROOT" install-doc
}

build_tarball() {
	title Building tarball
	do_or_die make dist
	do_or_die mv git-cola-"$VERSION".tar.gz "$RELEASES"
	do_or_die make app-tarball
	do_or_die mv git-cola-"$VERSION".app.tar.gz "$RELEASES"
}

build_win32_remotely() {
	title Building win32 remotely

	do_or_die ssh -p $WIN32_SSH_PORT "$WIN32_LOGIN" '
		PATH='"$WIN32_PYTHON"':$PATH
		cd '"$WIN32_COLA_DIR"'
		win32/create-installer.sh
	'
	do_or_die scp -P $WIN32_SSH_PORT \
		"$WIN32_LOGIN":"$WIN32_COLA_DIR"/"*.exe" .

	do_or_die ssh -p $WIN32_SSH_PORT \
		"$WIN32_LOGIN" "/bin/rm '$WIN32_COLA_DIR'/*.exe"

	do_or_die chmod 644 git-cola-"$VERSION".exe
	do_or_die mv git-cola-"$VERSION".exe "$RELEASES"
}

# Parse options
while test $# -gt 0; do
	case "$1" in
	--doc-dir)
		shift
		DOCUMENT_ROOT="$1"
		shift
		;;
	--all)
		shift
		do_tarball=true
		do_win32=true
		do_docs=true
		;;
	--tarball)
		shift
		do_tarball=true
		;;
	--doc)
		shift
		do_docs=true
		;;
	--win32)
		shift
		do_win32=true
		;;
	--win32-login)
		shift
		WIN32_LOGIN="$1"
		shift
		;;
	--win32-cola-dir)
		shift
		WIN32_COLA_DIR="$1"
		shift
		;;
	--win32-python-dir)
		shift
		WIN32_PYTHON="$1"
		shift
		;;
	--win32-port)
		shift
		WIN32_SSH_PORT="$1"
		shift
		;;
	--)
		shift
		break
		;;
	*)
		usage
		;;
	esac
done


if $do_tarball; then
	build_tarball
fi

if $do_win32; then
	build_win32_remotely
fi

if $do_docs; then
	build_docs
fi
