#!/bin/sh
. "$(dirname "$0")/common.sh"

usage () {
	echo "$0 <qtpy-repo>"
	exit 0
}

latest_tag () {
	git tag --sort=version:refname |
	tail -n 1
}

latest_tag_in_repo () {
	(cd "$1" && latest_tag)
}

update_repo () {
	(cd "$1" &&
		git remote -vv &&
		git fetch --verbose --prune --tags origin &&
		refname=$(latest_tag) &&
		git checkout "$refname"
	)
}

main () {
	if is_help "$1"
	then
		usage
	fi

	qtpy=qtpy
	qtpy_license=extras/qtpy

	if ! test -d "$qtpy" || ! test -d "$qtpy_license"
	then
		echo 1>&2 "error: $0 must be run from a git-cola worktree"
		exit 1
	fi

	repo="$1" &&
	update_repo "$repo" &&
	qtpy_tag=$(latest_tag_in_repo "$repo") &&

	cp -v \
		"$repo/AUTHORS.md" \
		"$repo/CHANGELOG.md" \
		"$repo/LICENSE.txt" \
		"$qtpy_license/" &&

	printf 'updating %s/ from %s/\n' "$qtpy" "$repo" &&
	rsync -r --delete --exclude=tests "$repo/qtpy/" "$qtpy/" &&
	git add -u -- "$qtpy" "$qtpy_license" &&
	git commit -sm"qtpy: update to spider-ide/qtpy $qtpy_tag"
}

main "$@"
