#!/bin/sh
# Setup PATH for git-osx-installer and other common
# locations such as /usr/local/bin
PATH="$PATH":/usr/local/bin:/usr/local/git/bin
export PATH

# Contents/MacOS/$this_script
# Contents/Resources
macos="$(dirname "$0")"
contents="$(dirname "$macos")"
exec python "$contents/Resources/bin/git-cola" --prompt
