#!/bin/sh
# This should work if used with both the default Python2.5
# from python.org and the default PyQt4 binary package
# from Riverbank.  Adjust accordingly.
/c/Python25/python.exe \
/c/Python25/Lib/site-packages/cola/bin/git-cola
