#!/bin/sh
cd $(dirname $0)/..
rootdir=$(pwd)
RUN_ALL=
PATH="$rootdir"/bin:"$PATH"
PYTHONPATH="$rootdir":"$PYTHONPATH"
export PATH
export PYTHONPATH
(
	cd t
	for unittest in t[0-9]*.py; do
		echo -n "$unittest"
		./"$unittest"
		status=$?
		if ! test $status -eq 0 && test -z "$RUN_ALL"; then
			echo " failed with exit code $?"
			exit -1
		else
			echo
		fi
	done

) 2>&1 | perl -e '

use Time::HiRes qw(gettimeofday);

my ($start_sec, $start_ms) = gettimeofday();

my $count = 0;
my @fail = ();
while(<>) {
	print;
	if ( /(\d+) tests/ ) {
		$count += $1;
	}
	elsif ( /failed/ ) {
		push @fail, $1;
	}
}

my ($end_sec, $end_ms) = gettimeofday();

my $min = 0;
my $sec = $end_sec - $start_sec;
my $secfrac = ( $end_ms - $start_ms ) * 100;

while ( $secfrac < 0.0 ) {
	$secfrac += 1000 * 100;
}

$secfrac = substr("$secfrac", 0, 2);

while ( $sec > 60 ) {
	$sec -= 60;
	$min++;
}

if ( @fail ) {
	print "\n";
	print "The following test FAILED:\n";
	print "-"x70 ."\n\t";
	print join("\n\t", @fail);
	print "\n";
}

print "\n";
print `git cola --version`;
print "-"x70 ."\n";
print "$count tests total\n";
print "$min min $sec.$secfrac sec total runtime\n\n";
'
test -z "$DEBUG" && rm -rf tmp
exit 0
