#!/usr/bin/env perl

use HTML::Entities;

my $date = `date`;
chomp $date;
print "# Generated by html2py.pl from HTML::Entities on $date\n";
print "ENTITIES = {\n";

for my $k (sort keys %HTML::Entities::char2entity) {

	my $int = ord($k);
	if ( $int > 255 ) {
		# These are either:
		# - outside of ord()'s 0-255 range
		# - used in ANSI color sequences handled by
		#   ugitutils` ansi_to_html.
		next;
	}
	my $v = $HTML::Entities::char2entity{$k};

	print "\t";
	print "chr($int)";
	print "\t:\t";
	print "'$v',\n";
}
print "}\n";
