#!/usr/bin/env python
import Common

def gen_install(path):
	def install():
		Common.install_files('PYMODS_UGIT', '', path)
	return install

def build(bld):
	# Create an intermediate version object for use as a dependency
	version = bld.create_obj('copy')
	version.source = 'version.sh'
	version.target = 'releaseversion.sh'

	vgen = bld.create_obj('command-output')
	vgen.dependencies = [ version ]
	vgen.command = 'gitversion.sh'
	vgen.stdin = 'gitversion.sh'
	vgen.stdout = 'version.py'
	vgen.install = gen_install('scripts/version.py')
