#!/usr/bin/env python
import os
import Common
import Params
from os.path import exists
from os.path import join

def gen_install(path):
	def install():
		Common.install_files('COLA_MODULES', '', path)
	return install

def build(bld):
	vgen = bld.create_obj('command-output')
	vgen.command = 'gitversion.sh'
	vgen.stdin = 'gitversion.sh'
	vgen.stdout = 'version.py'
	vgen.install = gen_install('../scripts/version.py')
	Common.install_files('COLA_APPS', '', 'cola.desktop')
