#!/usr/bin/env python
# Copyright(C) 2007, David Aguilar <davvid@gmail.com>
# License: GPL v2 or later
import os
import sys
import platform
import optparse
from os.path import join
from os.path import dirname

def setup_environment():
	"""Prepends sys.path with ugit's module path."""
	version = platform.python_version()
	try:
		thisfile = os.path.realpath(__file__)
		rootdir = dirname(dirname(thisfile))
		sys.path.insert(0, join(rootdir, 'share'))
	except:
		rootdir = dirname(os.getcwd())
		sys.path.insert(0, os.getcwd())
		sys.path.insert(0, rootdir)
		sys.path.insert(0, join(rootdir, 'share'))

def ugit_main():
	try:
		from PyQt4 import QtCore
		from PyQt4 import QtGui
	except ImportError:
		print "Sorry, you do not seem to have PyQt4 installed."
		print "Please install it before using ugit."
		print "e.g.:    sudo apt-get install python-qt4"
		sys.exit(-1)

	parser = optparse.OptionParser(usage='usage: %prog [options]')
	parser.add_option('-p', '--project',
			help='Path to a git repository',
			metavar='PROJECT',
			dest='project',
			default=None)

	parser.add_option('-v', '--version',
			help='Show ugit version',
			dest='version',
			default=False,
			action='store_true')
	opts, args = parser.parse_args()

	if opts.project and os.path.isdir(opts.project):
		os.chdir(opts.project)

	# This sets up sys.path so that the ugit modules can be found.
	setup_environment()

	from ugit.models import Model
	from ugit.views import View
	from ugit.controllers import Controller
	from ugit import utils

	if opts.version:
		from ugit.version import VERSION
		print "ugit version", VERSION
		sys.exit(0)

	app = QtGui.QApplication(sys.argv)
	app.setWindowIcon(QtGui.QIcon(utils.get_icon('git.png')))
	locale = str(QtCore.QLocale().system().name())
	qmfile = utils.get_qm_for_locale(locale)
	if os.path.exists(qmfile):
		translator = QtCore.QTranslator()
		translator.load(qmfile)
		app.installTranslator(translator)
	model = Model()
	view = View(app.activeWindow())
	ctl = Controller(model, view)
	view.show()
	sys.exit(app.exec_())

if __name__ == "__main__":
	ugit_main()
