#!/usr/bin/env python
import Common
def build(bld):
	# Compile the ugit support modules
	pyqt = bld.create_obj('py')
	pyqt.inst_var = 'PYMODS_UGIT'
	pyqt.find_sources_in_dirs('.')

	# Install the git-ugit launcher
	Common.install_files('BIN', '', 'git-ugit', chmod=0755)
	Common.symlink_as('BIN', 'git-ugit', 'ugit')
