#!/usr/bin/env python
import re
import os
from distutils.sysconfig import get_python_version

# Python site-packages helper
def get_site_packages(env):
	python_version = get_python_version()
	python_api = 'python' + python_version
	# Allow "env PYTHON=/usr/bin/python2.4 waf ..." overrides
	python = env['PYTHON']
	if python[-3:] != python_version:
		if re.match(r'\d+\.\d+', python[-3:]):
			python_api = os.path.basename(python)
	return os.path.join(env['PREFIX'], 'lib', python_api, 'site-packages')

def configure(conf):
	conf.check_tool('python')
	conf.env['PYTHON_SITE_PACKAGES'] = get_site_packages(conf.env)

def build(bld):
	# Compile all Python modules
	pyqt = bld.create_obj('py')
	pyqt.inst_var = 'PYTHON_SITE_PACKAGES'
	pyqt.find_sources_in_dirs('.')
